version: "3.1"
 
language: vi
 
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 500
  learning_rate: 0.002
  constrain_similarities: true
  entity_recognition: true
  use_masked_language_model: false
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 300
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1
 
policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 6
  epochs: 300
- name: TEDPolicy
  max_history: 6
  epochs: 300
  constrain_similarities: true
assistant_id: 20250612-202543-glad-sapwood